<a href="https://colab.research.google.com/github/PrashantSBasnet/L7_Maths/blob/master/240200701.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Step 1. Writing the student number in array form. Let us suppose it as A matrix.

In [2]:
A = np.array([[2, 4, 0],
              [2, 0, 0],
              [7, 0, 1]])

1. Determinant

In [3]:
requiredDet = np.linalg.det(A)
print("Determinant:", requiredDet)

Determinant: -7.999999999999998


2. To check whether it is singular or not, we know by the definition,

*   A square matrix whose determinant is zero is a singular matrix

Now, since the calculated determinant is not zero, the matrix is not a singular.



In [6]:
if requiredDet == 0:
    print("Matrix is singular (non-invertible).")
else:
    print("Matrix is not singular (invertible).")

Matrix is not singular (invertible).


3. Since the matrix is not singular, its inverse computable as follows:

In [9]:
if requiredDet != 0:
    Required_inverse = np.linalg.inv(A)
    print("Inverse of matrix A:")
    print(Required_inverse)
else:
    print("Matrix is not singular (invertible) and inverse cannot be calculated")

Inverse of matrix A:
[[ 0.    0.5   0.  ]
 [ 0.25 -0.25  0.  ]
 [-0.   -3.5   1.  ]]


4. Calculate and print the product of the original matrix and its
transpose.


*   Step1 : Finding the transpose matrix as follows:





In [10]:
A_transpose = np.transpose(A)



*   Step2: Finding the product of the original matrix and its transpose as follows:




In [11]:
product = np.dot(A_transpose, A)

In [12]:
print("Product of transpose(A) with A:")
print(product)

Product of transpose(A) with A:
[[57  8  7]
 [ 8 16  0]
 [ 7  0  1]]


5. Calculate and print the sum of the diagonal elements of the matrix
obtained in step 4


*   Step: We can use np.trace() function to find the sum of the diagonal



In [13]:
requiredSum_diagonal = np.trace(product) #as asked in the question
print ("Sum of the diagonal elements:", requiredSum_diagonal )


Sum of the diagonal elements: 74
