<a href="https://colab.research.google.com/github/PrashantSBasnet/L7_Maths/blob/master/240200701.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np

Step 1. Writing the student number in array form and appending '1' as given in the question.

In [34]:
#student id
number = 24020070

# Appending '1' to the student id as given in the question
new_number = int(str(number) + '1')

# Converting the number into a string
number_str = str(new_number)

# Splitting the string into individual characters
digits = list(number_str)

#converting the digits into int because det(A) doesn't support int
digits = [int(digit) for digit in digits]

# Reshaping the digits into a 3x3 matrix
A = np.array(digits).reshape(3, 3)

print(A)


[[2 4 0]
 [2 0 0]
 [7 0 1]]


In [33]:
Alternatively = np.array([[2,4,0],
                          [2,0,0],
                          [7,0,1]])
print (Alternatively)

[[2 4 0]
 [2 0 0]
 [7 0 1]]


1. Determinant

In [27]:
requiredDet = np.linalg.det(A)
print("Determinant:", requiredDet)

Determinant: -7.999999999999998


2. To check whether it is singular or not, we know by the definition,

*   A square matrix whose determinant is zero is a singular matrix

Now, since the calculated determinant is not zero, the matrix is not a singular.



In [ ]:
if requiredDet == 0:
    print("Matrix is singular (non-invertible).")
else:
    print("Matrix is not singular (invertible).")

Matrix is not singular (invertible).


3. Since the matrix is not singular, its inverse computable as follows:

In [ ]:
if requiredDet != 0:
    Required_inverse = np.linalg.inv(A)
    print("Inverse of matrix A:")
    print(Required_inverse)
else:
    print("Matrix is not singular (invertible) and inverse cannot be calculated")

Inverse of matrix A:
[[ 0.    0.5   0.  ]
 [ 0.25 -0.25  0.  ]
 [-0.   -3.5   1.  ]]


4. Calculate and print the product of the original matrix and its
transpose.


*   Step1 : Finding the transpose matrix as follows:





In [ ]:
A_transpose = np.transpose(A)



*   Step2: Finding the product of the original matrix and its transpose as follows:




In [ ]:
product = np.dot(A_transpose, A)

In [ ]:
print("Product of transpose(A) with A:")
print(product)

Product of transpose(A) with A:
[[57  8  7]
 [ 8 16  0]
 [ 7  0  1]]


5. Calculate and print the sum of the diagonal elements of the matrix
obtained in step 4


*   Step: We can use np.trace() function to find the sum of the diagonal



In [ ]:
requiredSum_diagonal = np.trace(product) #as asked in the question
print ("Sum of the diagonal elements:", requiredSum_diagonal )


Sum of the diagonal elements: 74
