<a href="https://colab.research.google.com/github/PrashantSBasnet/L7_Maths/blob/master/L7MathsPc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

**Matrices**

In [4]:
A = np.array([[3, 0,2],
              [2, 0,-2],
               [0,1,1]])

In [6]:
A_inv = np.linalg.inv(A)
print (A_inv)

[[ 0.2  0.2  0. ]
 [-0.2  0.3  1. ]
 [ 0.2 -0.3 -0. ]]


In [7]:
# Calculate the determinant
determinant = np.linalg.det(A)

# Print the determinant
print("Determinant of the matrix:", determinant)

Determinant of the matrix: 10.000000000000002


In [11]:
A = np.array([
             [1,2,3],
             [2,3,4],
             [3,4,5]
             ])

B = np.array([
             [4,5,6],
             [5,6,7],
             [6,7,8]
             ])


print (np.dot(A,B))

[[32 38 44]
 [47 56 65]
 [62 74 86]]


In [ ]:
A = np.array([[1, 1,1],
              [2, 2,2],
               [3,3,3]])



In [12]:
print (np.exp(2))

7.38905609893065


In [13]:
print (np.log(10))

2.302585092994046


In [14]:
a = np.array([1,2,3])
print (a)

[1 2 3]


In [15]:
b = np.array([4,5,6])

In [17]:
print (np.column_stack([a,b]))

[[1 4]
 [2 5]
 [3 6]]


In [20]:
print (np.vstack([a,b]).T)

[[1 4]
 [2 5]
 [3 6]]


In [22]:
print (np.row_stack([a,b]))

[[1 2 3]
 [4 5 6]]


In [23]:
print (np.vstack([a,b]))

[[1 2 3]
 [4 5 6]]


In [27]:
x = np.linspace(-np.pi, np.pi, 10)
print(x)
print(x[9])
print(x[0]) # first element
print(x[2]) # third element
print(x[-1]) # last element
print(x[-2]) # second to last element

[-3.14159265 -2.44346095 -1.74532925 -1.04719755 -0.34906585  0.34906585
  1.04719755  1.74532925  2.44346095  3.14159265]
3.141592653589793
-3.141592653589793
-1.7453292519943295
3.141592653589793
2.443460952792061


**Finding Projection**

In [28]:
import numpy as np

# Define the vectors
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

# Calculate the dot product of vector_a and vector_b
dot_product = np.dot(vector_a, vector_b)

# Calculate the magnitude squared of vector_b
magnitude_b_squared = np.dot(vector_b, vector_b)

# Calculate the projection of vector_a onto vector_b
projection = (dot_product / magnitude_b_squared) * vector_b

print("Projection of vector_a onto vector_b:", projection)


Projection of vector_a onto vector_b: [1.66233766 2.07792208 2.49350649]
